### PR TITLE
2024 radiuss tutorial updates

### PR DESCRIPTION
**Pull request by dyokelson**
Fixed a few of the steps in the README, also adjusted a couple plots in notebook 1

### CODE REVIEW

**Comment by dyokelson** [comment]
I am debating suppressing all the FutureWarnings from Pandas 3 or not...any thoughts?

**Review by ilumsden — CHANGES_REQUESTED** [review]
Only one change I'd request:

Please do suppress all the Pandas 3 `FutureWarning`s

**Review by michaelmckinsey1 — APPROVED** [review]
I approve the notebook changes. Ian would know about the docker/podman

**Review by ilumsden — APPROVED** [review]
LGTM.

**Comment by ilumsden** [comment]
@dyokelson @pearce8 one of you can merge this PR

**Pull request merged**
